version: '3'
services:
  redis-master-1:
    image: bitnami/redis
    user: root # run a Bitnami non-root container image as a root container image
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redisai.so:/usr/lib/redis/modules/redisai.so
    ports:
     - 7001:7001
     - 17001:17001
    network_mode: "redis-cluster-net"
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    command: redis-server /usr/local/etc/redis/redis.conf --port 7001 --protected-mode no
    
  redis-replica-1:
    image: bitnami/redis
    user: root # run a Bitnami non-root container image as a root container image
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redisai.so:/usr/lib/redis/modules/redisai.so
    ports:
      - 7002:7002
      - 17002:17002
    network_mode: "redis-cluster-net"
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master-1
      - ALLOW_EMPTY_PASSWORD=yes
    command: redis-server /usr/local/etc/redis/redis.conf --port 7002 --protected-mode no
    depends_on:
      - redis-master-1


  redis-master-2:
    image: bitnami/redis
    user: root # run a Bitnami non-root container image as a root container image
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redisai.so:/usr/lib/redis/modules/redisai.so
    ports:
     - 7003:7003
     - 17003:17003
    network_mode: "redis-cluster-net"
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    command: redis-server /usr/local/etc/redis/redis.conf --port 7003 --protected-mode no

  redis-replica-2:
    image: bitnami/redis
    user: root # run a Bitnami non-root container image as a root container image
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redisai.so:/usr/lib/redis/modules/redisai.so
    ports:
      - 7004:7004
      - 17004:17004
    network_mode: "redis-cluster-net"
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master-2
      - ALLOW_EMPTY_PASSWORD=yes
    command: redis-server /usr/local/etc/redis/redis.conf --port 7004 --protected-mode no
    depends_on:
      - redis-master-2


  redis-master-3:
    image: bitnami/redis
    user: root # run a Bitnami non-root container image as a root container image
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redisai.so:/usr/lib/redis/modules/redisai.so
    ports:
     - 7005:7005
     - 17005:17005
    network_mode: "redis-cluster-net"
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    command: redis-server /usr/local/etc/redis/redis.conf --port 7005 --protected-mode no

  redis-replica-3:
    image: bitnami/redis
    user: root # run a Bitnami non-root container image as a root container image
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redisai.so:/usr/lib/redis/modules/redisai.so
    ports:
      - 7006:7006
      - 17006:17006
    network_mode: "redis-cluster-net"
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master-3
      - ALLOW_EMPTY_PASSWORD=yes
    command: redis-server /usr/local/etc/redis/redis.conf --port 7006 --protected-mode no
    depends_on:
      - redis-master-3